// ============================================================================
// ARGOS — matrice du profil « direx » (ADR 0022) — FICHIER GÉNÉRÉ
//
// Source : docs/matrice-roles-direx.csv (la grille se corrige dans le tableur,
// puis :  node apps/api/scripts/direx-matrix.mjs). Ne pas éditer à la main.
// Un rôle absent d'une ligne n'a aucun droit sur la fonctionnalité.
// ============================================================================
import type { Feature } from "@/shared/permissions";
import type { Role } from "@/shared/profiles";

const V = "V", VM = "VM", AMV = "AMV", ALL = "AMRV", FULL = "AMRVD";

export const DIREX_MATRIX: Record<Feature, Partial<Record<Role, string>>> = {
  dashboard: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: V, pct_log: V, pct_rens: V, pco_chef: V, pco_ops: V, pco_log: V, pco_rens_com: V },
  dash_incident: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: V, pct_log: V, pct_rens: V, pco_chef: V, pco_ops: V, pco_log: V, pco_rens_com: V },
  dash_hospital: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: V, pct_log: V, pct_rens: V, pco_chef: V, pco_ops: V, pco_log: V, pco_rens_com: V },
  dash_shelter: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: V, pct_log: V, pct_rens: V, pco_chef: V, pco_ops: V, pco_log: V, pco_rens_com: V },
  dash_morgue: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: V, pct_log: V, pct_rens: V, pco_chef: V, pco_ops: V, pco_log: V, pco_rens_com: V },
  dash_unit: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: V, pct_log: V, pct_rens: V, pco_chef: V, pco_ops: V, pco_log: V, pco_rens_com: V },
  map: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: V, pct_log: V, pct_rens: V, pco_chef: V, pco_ops: V, pco_log: V, pco_rens_com: V },
  incidents: { direx_chef: ALL, direx_eval: V, direx_anim: ALL, direx_rls: V, pcfar_chef: ALL, pcfar_ops: AMV, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: ALL, pcf_ops: AMV, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: VM, pct_ops: V, pct_log: V, pct_rens: V, pco_chef: VM, pco_ops: V, pco_log: V, pco_rens_com: V },
  subincidents: { direx_chef: ALL, direx_eval: V, direx_anim: ALL, direx_rls: V, pcfar_chef: ALL, pcfar_ops: AMV, pcfar_log: V, pcfar_planif_rens: AMV, pcfar_synth: V, pcf_chef: ALL, pcf_ops: AMV, pcf_log: V, pcf_planif_rens: AMV, pcf_synth: V, pct_chef: ALL, pct_ops: AMV, pct_log: V, pct_rens: V, pco_chef: ALL, pco_ops: AMV, pco_log: V, pco_rens_com: V },
  victims: { direx_chef: ALL, direx_eval: V, direx_anim: ALL, direx_rls: V, pcfar_chef: ALL, pcfar_ops: AMV, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: ALL, pcf_ops: AMV, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: ALL, pct_ops: AMV, pct_log: AMV, pct_rens: V, pco_chef: ALL, pco_ops: AMV, pco_log: AMV, pco_rens_com: V },
  hospinet: { direx_chef: FULL, direx_eval: V, direx_anim: FULL, direx_rls: FULL, pcfar_chef: FULL, pcfar_ops: FULL, pcfar_log: FULL, pcfar_planif_rens: FULL, pcfar_synth: V, pcf_chef: FULL, pcf_ops: FULL, pcf_log: FULL, pcf_planif_rens: FULL, pcf_synth: V, pct_chef: FULL, pct_ops: FULL, pct_log: FULL, pct_rens: FULL, pco_chef: FULL, pco_ops: FULL, pco_log: FULL, pco_rens_com: FULL },
  shelters: { direx_chef: FULL, direx_eval: V, direx_anim: FULL, direx_rls: FULL, pcfar_chef: FULL, pcfar_ops: FULL, pcfar_log: FULL, pcfar_planif_rens: FULL, pcfar_synth: V, pcf_chef: FULL, pcf_ops: FULL, pcf_log: FULL, pcf_planif_rens: FULL, pcf_synth: V, pct_chef: FULL, pct_ops: FULL, pct_log: FULL, pct_rens: FULL, pco_chef: FULL, pco_ops: FULL, pco_log: FULL, pco_rens_com: FULL },
  morgue: { direx_chef: FULL, direx_eval: V, direx_anim: FULL, direx_rls: FULL, pcfar_chef: FULL, pcfar_ops: FULL, pcfar_log: FULL, pcfar_planif_rens: FULL, pcfar_synth: V, pcf_chef: FULL, pcf_ops: FULL, pcf_log: FULL, pcf_planif_rens: FULL, pcf_synth: V, pct_chef: FULL, pct_ops: FULL, pct_log: FULL, pct_rens: FULL, pco_chef: FULL, pco_ops: FULL, pco_log: FULL, pco_rens_com: FULL },
  units: { direx_chef: AMV, direx_eval: V, direx_anim: AMV, direx_rls: AMV, pcfar_chef: AMV, pcfar_ops: AMV, pcfar_log: AMV, pcfar_planif_rens: AMV, pcfar_synth: V, pcf_chef: AMV, pcf_ops: AMV, pcf_log: AMV, pcf_planif_rens: AMV, pcf_synth: V, pct_chef: AMV, pct_ops: AMV, pct_log: AMV, pct_rens: AMV, pco_chef: AMV, pco_ops: AMV, pco_log: AMV, pco_rens_com: AMV },
  equipment: { direx_chef: V, direx_eval: V, direx_anim: AMV, direx_rls: AMV, pcfar_chef: V, pcfar_ops: V, pcfar_log: AMV, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: AMV, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: V, pct_log: AMV, pct_rens: V, pco_chef: V, pco_ops: V, pco_log: AMV, pco_rens_com: V },
  teams: { direx_chef: AMV, direx_eval: V, direx_anim: AMV, direx_rls: AMV, pcfar_chef: AMV, pcfar_ops: AMV, pcfar_log: AMV, pcfar_planif_rens: AMV, pcfar_synth: V, pcf_chef: AMV, pcf_ops: AMV, pcf_log: AMV, pcf_planif_rens: AMV, pcf_synth: V, pct_chef: AMV, pct_ops: AMV, pct_log: AMV, pct_rens: AMV, pco_chef: AMV, pco_ops: AMV, pco_log: AMV, pco_rens_com: AMV },
  comms: { direx_chef: VM, direx_eval: VM, direx_anim: VM, direx_rls: VM, pcfar_chef: VM, pcfar_ops: VM, pcfar_log: VM, pcfar_planif_rens: VM, pcfar_synth: VM, pcf_chef: VM, pcf_ops: VM, pcf_log: VM, pcf_planif_rens: VM, pcf_synth: VM, pct_chef: VM, pct_ops: VM, pct_log: VM, pct_rens: VM, pco_chef: VM, pco_ops: VM, pco_log: VM, pco_rens_com: VM },
  reports: { direx_chef: ALL, direx_eval: AMV, direx_anim: V, direx_rls: AMV, pcfar_chef: ALL, pcfar_ops: AMV, pcfar_log: AMV, pcfar_planif_rens: AMV, pcfar_synth: ALL, pcf_chef: ALL, pcf_ops: AMV, pcf_log: AMV, pcf_planif_rens: AMV, pcf_synth: ALL, pct_chef: VM, pct_ops: V, pct_log: V, pct_rens: AMV, pco_chef: VM, pco_ops: V, pco_log: V, pco_rens_com: AMV },
  analytics: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: V, pct_log: V, pct_rens: V, pco_chef: V, pco_ops: V, pco_log: V, pco_rens_com: V },
  assistant: { direx_chef: VM, direx_eval: VM, direx_anim: VM, direx_rls: VM, pcfar_chef: VM, pcfar_ops: VM, pcfar_log: VM, pcfar_planif_rens: VM, pcfar_synth: VM, pcf_chef: VM, pcf_ops: VM, pcf_log: VM, pcf_planif_rens: VM, pcf_synth: VM, pct_chef: VM, pct_ops: VM, pct_log: VM, pct_rens: VM, pco_chef: VM, pco_ops: VM, pco_log: VM, pco_rens_com: VM },
  users: {  },
  settings: {  },
  assign: { direx_chef: V, direx_eval: V, direx_anim: AMV, direx_rls: V, pcfar_chef: AMV, pcfar_ops: AMV, pcfar_log: AMV, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: AMV, pcf_ops: AMV, pcf_log: AMV, pcf_planif_rens: V, pcf_synth: V, pct_chef: AMV, pct_ops: AMV, pct_log: AMV, pct_rens: V, pco_chef: AMV, pco_ops: AMV, pco_log: AMV, pco_rens_com: V },
  deploy: { direx_chef: V, direx_eval: V, direx_anim: AMV, direx_rls: V, pcfar_chef: AMV, pcfar_ops: AMV, pcfar_log: AMV, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: AMV, pcf_ops: AMV, pcf_log: AMV, pcf_planif_rens: V, pcf_synth: V, pct_chef: AMV, pct_ops: AMV, pct_log: AMV, pct_rens: AMV, pco_chef: AMV, pco_ops: AMV, pco_log: AMV, pco_rens_com: AMV },
  resources: { direx_chef: V, direx_eval: V, direx_anim: ALL, direx_rls: AMV, pcfar_chef: V, pcfar_ops: ALL, pcfar_log: ALL, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: ALL, pcf_log: ALL, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: ALL, pct_log: ALL, pct_rens: ALL, pco_chef: V, pco_ops: ALL, pco_log: ALL, pco_rens_com: ALL },
  weather: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: V, pct_log: V, pct_rens: V, pco_chef: V, pco_ops: V, pco_log: V, pco_rens_com: V },
  plume: { direx_chef: AMV, direx_eval: V, direx_anim: AMV, direx_rls: AMV, pcfar_chef: V, pcfar_ops: V, pcfar_planif_rens: AMV, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_planif_rens: AMV, pcf_synth: V, pct_chef: V, pct_rens: V, pco_chef: V, pco_rens_com: V },
  dispatch: { direx_chef: V, direx_eval: V, direx_anim: AMV, direx_rls: AMV, pcfar_chef: AMV, pcfar_ops: AMV, pcfar_log: AMV, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: AMV, pcf_ops: AMV, pcf_log: AMV, pcf_planif_rens: V, pcf_synth: V, pct_chef: AMV, pct_ops: AMV, pct_log: AMV, pco_chef: AMV, pco_ops: AMV, pco_log: AMV },
  triage: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: AMV, pct_rens: V, pco_chef: V, pco_ops: AMV, pco_rens_com: V },
  ics: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: AMV, pcfar_log: V, pcfar_planif_rens: AMV, pcfar_synth: V, pcf_chef: V, pcf_ops: AMV, pcf_log: V, pcf_planif_rens: AMV, pcf_synth: V, pct_chef: V, pct_ops: AMV, pct_rens: V, pco_chef: V, pco_ops: AMV, pco_rens_com: V },
  damage: { direx_chef: V, direx_eval: V, direx_anim: AMV, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: AMV, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: AMV, pcf_synth: V, pct_chef: V, pct_ops: V, pct_rens: AMV, pco_chef: V, pco_ops: V, pco_rens_com: AMV },
  orsec: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: AMV, pcfar_ops: AMV, pcfar_log: V, pcfar_planif_rens: ALL, pcfar_synth: V, pcf_chef: AMV, pcf_ops: AMV, pcf_log: V, pcf_planif_rens: ALL, pcf_synth: V, pct_chef: AMV, pco_chef: AMV },
  plans: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: AMV, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: ALL, pcfar_synth: V, pcf_chef: AMV, pcf_ops: V, pcf_log: V, pcf_planif_rens: ALL, pcf_synth: V, pct_chef: V, pco_chef: V },
  personnel: { direx_eval: V, direx_anim: AMV, direx_rls: AMV, pcfar_log: AMV, pcfar_planif_rens: V, pcfar_synth: V, pcf_log: AMV, pcf_planif_rens: V, pcf_synth: V, pct_log: AMV, pco_log: AMV },
  workorders: { direx_eval: V, direx_rls: AMV, pcfar_log: AMV, pcfar_planif_rens: V, pcfar_synth: V, pcf_log: AMV, pcf_planif_rens: V, pcf_synth: V, pct_log: AMV, pco_log: AMV },
  seismic: { direx_chef: V, direx_eval: V, direx_anim: V, direx_rls: V, pcfar_chef: V, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: V, pcf_ops: V, pcf_log: V, pcf_planif_rens: V, pcf_synth: V, pct_chef: V, pct_ops: V, pco_chef: V, pco_ops: V },
  audit: { direx_chef: V, direx_eval: V, direx_rls: V },
  aviation: { direx_chef: AMV, direx_eval: V, direx_anim: AMV, direx_rls: AMV, pcfar_chef: AMV, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: AMV, pcfar_synth: V, pcf_chef: AMV, pcf_ops: V, pcf_log: V, pcf_planif_rens: AMV, pcf_synth: V, pct_chef: AMV, pct_ops: V, pct_log: V, pct_rens: V, pco_chef: AMV, pco_ops: V, pco_log: V, pco_rens_com: V },
  tracking: { direx_chef: AMV, direx_eval: V, direx_anim: AMV, direx_rls: AMV, pcfar_chef: AMV, pcfar_ops: AMV, pcfar_log: V, pcfar_planif_rens: AMV, pcfar_synth: V, pcf_chef: AMV, pcf_ops: AMV, pcf_log: V, pcf_planif_rens: AMV, pcf_synth: V, pct_chef: AMV, pct_ops: V, pct_log: V, pct_rens: AMV, pco_chef: AMV, pco_ops: V, pco_log: V, pco_rens_com: AMV },
  comms_admin: { direx_chef: AMV, direx_rls: AMV, pco_rens_com: AMV },
  map_edit: { direx_chef: AMV, direx_anim: AMV, direx_rls: V, pcfar_chef: AMV, pcfar_ops: AMV, pcfar_planif_rens: V, pcf_chef: AMV, pcf_ops: AMV, pcf_planif_rens: V, pct_chef: AMV, pct_ops: AMV, pct_log: AMV, pct_rens: AMV, pco_chef: AMV, pco_ops: AMV, pco_log: AMV, pco_rens_com: AMV },
  nrbc: { direx_chef: AMV, direx_eval: V, direx_anim: AMV, direx_rls: AMV, pcfar_chef: AMV, pcfar_ops: V, pcfar_log: V, pcfar_planif_rens: AMV, pcfar_synth: V, pcf_chef: AMV, pcf_ops: V, pcf_log: V, pcf_planif_rens: AMV, pcf_synth: V, pct_chef: AMV, pct_ops: V, pct_log: V, pct_rens: AMV, pco_chef: AMV, pco_ops: V, pco_log: V, pco_rens_com: AMV },
  missions: { direx_chef: V, direx_eval: V, direx_anim: AMV, direx_rls: V, pcfar_chef: AMV, pcfar_ops: AMV, pcfar_log: AMV, pcfar_planif_rens: V, pcfar_synth: V, pcf_chef: AMV, pcf_ops: AMV, pcf_log: AMV, pcf_planif_rens: V, pcf_synth: V, pct_chef: AMV, pct_ops: AMV, pct_log: AMV, pct_rens: V, pco_chef: AMV, pco_ops: AMV, pco_log: AMV, pco_rens_com: V },
};
