import type { Substance } from "@/modules/nrbc/nrbc.types";

// ============================================================================
// ARGOS — BIBLIOTHÈQUE DE SUBSTANCES DANGEREUSES (lot N-3)
//
// CE QUE CE FICHIER EST, ET CE QU'IL N'EST PAS.
//
// CAMEO Chemicals (NOAA) publie environ six mille fiches. ARGOS ne peut pas les
// interroger : aucun appel sortant vers un tiers n'est admis à l'exécution
// (ADR 0006, MASTER_PLAN §4.3). Ce fichier n'est donc PAS une copie de CAMEO.
// C'est la FORME de ses données, remplie de ce qu'on peut honnêtement affirmer,
// avec un chemin explicite pour y verser les fiches réelles.
//
// DEUX JEUX DE DONNÉES DISTINCTS, DEUX PROVENANCES DISTINCTES :
//
//   `sheet` + `sheetVerified`    la FICHE — aspect, comportement du nuage,
//                                effets, réactivité, protection. C'est ce que
//                                donne CAMEO Chemicals.
//   `small`/`large` + `ergVerified`  les DISTANCES — table 1 de l'ERG 2024.
//                                C'est un autre document, une autre autorité.
//
// Les confondre ferait croire qu'une fiche juste vaut distance juste. Elles sont
// donc marquées séparément, et l'interface affiche les deux.
//
// POURQUOI CERTAINES SUBSTANCES N'ONT PAS DE DISTANCES. Les onze premières les
// portent depuis le lot NRBC initial. Les vingt ajoutées ici ne les portent PAS :
// leurs valeurs n'ont pas été relevées sur la table 1, et une distance
// d'isolement plausible mais fausse est le genre d'erreur qui ne se découvre
// qu'une fois le périmètre posé trop court. Le gabarit ERG du panache est donc
// indisponible pour elles, et l'interface le dit — le gabarit ATP-45, qui ne
// dépend que du vent, reste disponible.
//
// COMMENT COMPLÉTER (procédure d'état-major) :
//   1. ouvrir la fiche CAMEO Chemicals de la substance (numéro CAS ci-dessous) ;
//   2. confronter `sheet`, corriger, passer `sheetVerified: true` ;
//   3. relever la table 1 de l'ERG 2024 pour le petit et le grand déversement,
//      renseigner `small`/`large`, passer `ergVerified: true`.
// Le port `SubstanceCatalog` permettra demain d'alimenter une table Postgres
// sans toucher au service.
//
// « Grand déversement » : retenir le PIRE CAS de la ligne (wagon /
// semi-remorque), pas la citerne moyenne — un état-major planifie sur
// l'enveloppe, pas sur l'optimisme.
// ============================================================================

/**
 * État de vérification de la bibliothèque, calculé et affiché tel quel.
 *
 * Aujourd'hui : deux jeux de distances relevés, aucune fiche confrontée. Ce
 * n'est pas satisfaisant — c'est exact, et le dire est la seule façon que ça le
 * devienne.
 */
export function libraryProvenance(list: Substance[]) {
  return {
    total: list.length,
    ergVerified: list.filter((s) => s.ergVerified).length,
    withErgDistances: list.filter((s) => s.small && s.large).length,
    sheetVerified: list.filter((s) => s.sheetVerified).length,
    withSheet: list.filter((s) => s.sheet).length,
  };
}

export const SUBSTANCES: Substance[] = [
  // ==========================================================================
  // GAZ TOXIQUES PAR INHALATION — les onze d'origine, fiches ajoutées ici
  // ==========================================================================
  {
    id: "chlorine",
    un: "1017",
    cas: "7782-50-5",
    ergGuide: "124",
    labels: { fr: "Chlore", ar: "الكلور", en: "Chlorine" },
    synonyms: ["Cl2", "dichlore", "chlorine gas"],
    hazardClass: "2.3",
    state: "gas",
    small: { isolationM: 61, protectDayKm: 0.32, protectNightKm: 1.45 },
    large: { isolationM: 914, protectDayKm: 9.65, protectNightKm: 11.27 },
    ergVerified: true,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz jaune-vert, odeur suffocante d'eau de Javel, perceptible bien avant le seuil de danger.",
      vaporDensity: 2.5,
      boilingPointC: -34,
      behaviour:
        "Deux fois et demie plus lourd que l'air : le nuage rampe au sol, s'accumule dans les caves, " +
        "les fosses et les points bas. Évacuer vers les hauteurs, jamais vers le bas.",
      health:
        "Irritation immédiate des yeux et des voies respiratoires ; œdème pulmonaire pouvant survenir " +
        "plusieurs heures après une exposition d'apparence bénigne — toute victime exposée est mise en observation.",
      fire: "Ininflammable, mais entretient la combustion. De nombreux matériaux brûlent dans le chlore.",
      reactivity:
        "Réagit violemment avec l'ammoniac, les hydrocarbures, les métaux finement divisés. Forme des acides " +
        "corrosifs au contact de l'humidité.",
      ppe: "ARI et combinaison étanche aux gaz. Le masque filtrant ne suffit pas en zone d'exclusion.",
    },
  },
  {
    id: "ammonia",
    un: "1005",
    cas: "7664-41-7",
    ergGuide: "125",
    labels: { fr: "Ammoniac anhydre", ar: "الأمونيا اللامائية", en: "Anhydrous ammonia" },
    synonyms: ["NH3", "ammoniac liquéfié"],
    hazardClass: "2.3",
    state: "gas",
    small: { isolationM: 30, protectDayKm: 0.16, protectNightKm: 0.16 },
    // Jour 1,0 mille = 1,61 km ; nuit 2,6 milles = 4,18 km (table 3, wagon-citerne,
    // vent faible). La valeur de jour recopiait CELLE DE NUIT jusqu'au lot N-3c :
    // erreur trouvée en confrontant la saisie à la base ERG, pas en la relisant.
    large: { isolationM: 305, protectDayKm: 1.61, protectNightKm: 4.18 },
    ergVerified: true,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore, odeur piquante caractéristique, détectable très en deçà du seuil de danger.",
      vaporDensity: 0.6,
      boilingPointC: -33,
      behaviour:
        "Plus léger que l'air et donc censé s'élever — mais à la sortie d'une citerne sous pression, " +
        "l'aérosol froid est plus dense et rampe d'abord. Ne pas se fier à la seule densité.",
      health: "Brûlures caustiques des yeux et des muqueuses ; œdème pulmonaire aux fortes concentrations.",
      fire: "Inflammable en espace confiné dans une plage étroite. Les récipients exposés au feu peuvent éclater.",
      reactivity: "Réagit violemment avec le chlore, les acides forts, les halogènes. Corrode le cuivre et ses alliages.",
      ppe: "ARI et tenue étanche aux vapeurs. L'eau en rideau abat le nuage mais génère un effluent alcalin à recueillir.",
    },
  },
  {
    id: "sulfur-dioxide",
    un: "1079",
    cas: "7446-09-5",
    ergGuide: "125",
    labels: { fr: "Dioxyde de soufre", ar: "ثاني أكسيد الكبريت", en: "Sulfur dioxide" },
    synonyms: ["SO2", "anhydride sulfureux"],
    hazardClass: "2.3",
    state: "gas",
    small: { isolationM: 30, protectDayKm: 0.19, protectNightKm: 0.8 },
    large: { isolationM: 152, protectDayKm: 1.4, protectNightKm: 4.5 },
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore, odeur âcre d'allumette craquée.",
      vaporDensity: 2.3,
      boilingPointC: -10,
      behaviour: "Plus lourd que l'air : stagne dans les points bas et les locaux enterrés.",
      health: "Bronchospasme immédiat, surtout chez l'asthmatique ; œdème pulmonaire retardé.",
      fire: "Ininflammable.",
      reactivity: "Forme de l'acide sulfureux au contact de l'eau. Attaque de nombreux métaux en présence d'humidité.",
      ppe: "ARI et tenue étanche aux vapeurs.",
    },
  },
  {
    id: "hydrogen-sulfide",
    un: "1053",
    cas: "7783-06-4",
    ergGuide: "117",
    labels: { fr: "Sulfure d'hydrogène", ar: "كبريتيد الهيدروجين", en: "Hydrogen sulfide" },
    synonyms: ["H2S", "hydrogène sulfuré", "gaz des égouts"],
    hazardClass: "2.3",
    state: "gas",
    small: { isolationM: 30, protectDayKm: 0.16, protectNightKm: 0.5 },
    large: { isolationM: 213, protectDayKm: 1.5, protectNightKm: 4.0 },
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore, odeur d'œuf pourri à basse concentration.",
      vaporDensity: 1.2,
      boilingPointC: -60,
      behaviour:
        "Plus lourd que l'air, s'accumule en fond de cuve, d'égout et de fosse. PARALYSE L'ODORAT aux " +
        "concentrations dangereuses : l'absence d'odeur ne signifie pas l'absence de danger, elle signifie souvent le contraire.",
      health: "Aux fortes concentrations, perte de connaissance en quelques inspirations puis arrêt respiratoire.",
      fire: "Très inflammable. Brûle en dégageant du dioxyde de soufre.",
      reactivity: "Réagit avec les oxydants forts. Corrode les aciers (fragilisation par l'hydrogène).",
      ppe: "ARI obligatoire. Détection portative continue — l'odorat n'est pas un détecteur.",
    },
  },
  {
    id: "phosgene",
    un: "1076",
    cas: "75-44-5",
    ergGuide: "125",
    labels: { fr: "Phosgène", ar: "الفوسجين", en: "Phosgene" },
    synonyms: ["COCl2", "chlorure de carbonyle"],
    hazardClass: "2.3",
    state: "gas",
    small: { isolationM: 100, protectDayKm: 0.6, protectNightKm: 2.6 },
    large: { isolationM: 610, protectDayKm: 5.5, protectNightKm: 9.0 },
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore, odeur de foin fraîchement coupé — trompeuse, presque agréable.",
      vaporDensity: 3.4,
      boilingPointC: 8,
      behaviour: "Trois fois et demie plus lourd que l'air : rampe longuement et stagne.",
      health:
        "Irritation initiale FAIBLE puis œdème pulmonaire retardé de 2 à 24 h, souvent mortel. Une victime " +
        "qui va bien sur zone n'est pas une victime indemne : évacuation et surveillance systématiques.",
      fire: "Ininflammable.",
      reactivity: "S'hydrolyse lentement en acide chlorhydrique. Se forme lors de la combustion de solvants chlorés.",
      ppe: "ARI et tenue étanche aux gaz, sans exception.",
    },
  },
  {
    id: "hydrogen-cyanide",
    un: "1051",
    cas: "74-90-8",
    ergGuide: "117",
    labels: { fr: "Cyanure d'hydrogène", ar: "سيانيد الهيدروجين", en: "Hydrogen cyanide" },
    synonyms: ["HCN", "acide cyanhydrique", "acide prussique"],
    hazardClass: "6.1",
    state: "liquid",
    small: { isolationM: 60, protectDayKm: 0.3, protectNightKm: 1.0 },
    large: { isolationM: 400, protectDayKm: 2.5, protectNightKm: 6.5 },
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide très volatil ou gaz, odeur d'amande amère — non perçue par une partie de la population.",
      vaporDensity: 0.9,
      boilingPointC: 26,
      behaviour: "Vapeur de densité proche de l'air, se disperse au vent mais stagne en espace confiné.",
      health: "Asphyxiant cellulaire : perte de connaissance et arrêt cardiaque en quelques minutes. Antidote spécifique.",
      fire: "Très inflammable.",
      reactivity: "Peut polymériser violemment en présence de bases. Dégagé par les acides au contact de cyanures.",
      ppe: "ARI et tenue étanche. Prévoir l'antidote sur le point de regroupement des victimes.",
    },
  },
  {
    id: "hydrogen-fluoride",
    un: "1052",
    cas: "7664-39-3",
    ergGuide: "125",
    labels: { fr: "Fluorure d'hydrogène anhydre", ar: "فلوريد الهيدروجين", en: "Hydrogen fluoride" },
    synonyms: ["HF", "acide fluorhydrique anhydre"],
    hazardClass: "8",
    state: "liquid",
    small: { isolationM: 30, protectDayKm: 0.2, protectNightKm: 0.6 },
    large: { isolationM: 300, protectDayKm: 2.0, protectNightKm: 5.0 },
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide fumant ou gaz incolore, odeur âcre.",
      vaporDensity: 0.7,
      boilingPointC: 20,
      behaviour: "Fume abondamment à l'air humide. Le nuage blanc marque l'étendue du rejet.",
      health:
        "Brûlures profondes et douloureuses APRÈS un délai ; le fluorure capte le calcium sanguin et provoque " +
        "des troubles du rythme cardiaque. Gluconate de calcium à prévoir.",
      fire: "Ininflammable.",
      reactivity: "Attaque le verre, le béton et la plupart des métaux. Ne jamais confiner dans un récipient en verre.",
      ppe: "Tenue étanche résistante au HF, ARI. Gluconate de calcium en gel sur le point de décontamination.",
    },
  },
  {
    id: "hydrogen-chloride",
    un: "1050",
    cas: "7647-01-0",
    ergGuide: "125",
    labels: { fr: "Chlorure d'hydrogène anhydre", ar: "كلوريد الهيدروجين", en: "Hydrogen chloride" },
    synonyms: ["HCl", "acide chlorhydrique anhydre"],
    hazardClass: "2.3",
    state: "gas",
    small: { isolationM: 30, protectDayKm: 0.2, protectNightKm: 0.7 },
    large: { isolationM: 275, protectDayKm: 1.8, protectNightKm: 4.5 },
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore fumant à l'air humide, odeur piquante.",
      vaporDensity: 1.3,
      boilingPointC: -85,
      behaviour: "Plus lourd que l'air ; forme un brouillard acide dense et très visible.",
      health: "Brûlures des voies respiratoires et des yeux ; œdème pulmonaire aux fortes concentrations.",
      fire: "Ininflammable.",
      reactivity: "Très corrosif pour les métaux, dégage de l'hydrogène (risque d'explosion en espace clos).",
      ppe: "ARI et tenue étanche aux vapeurs acides.",
    },
  },
  {
    id: "ethylene-oxide",
    un: "1040",
    cas: "75-21-8",
    ergGuide: "119",
    labels: { fr: "Oxyde d'éthylène", ar: "أكسيد الإيثيلين", en: "Ethylene oxide" },
    synonyms: ["EtO", "oxirane"],
    hazardClass: "2.3",
    state: "gas",
    small: { isolationM: 30, protectDayKm: 0.2, protectNightKm: 0.6 },
    large: { isolationM: 150, protectDayKm: 1.2, protectNightKm: 3.0 },
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore, odeur éthérée sucrée.",
      vaporDensity: 1.5,
      boilingPointC: 11,
      behaviour: "Plus lourd que l'air. Plage d'explosivité exceptionnellement large.",
      health: "Irritant, cancérogène avéré. Exposition à documenter pour le suivi médical des intervenants.",
      fire: "Extrêmement inflammable ; peut se décomposer de façon explosive sans air, sous l'effet de la chaleur.",
      reactivity: "Polymérise violemment en présence d'acides, de bases, d'oxydes métalliques.",
      ppe: "ARI, tenue étanche, matériel antidéflagrant.",
    },
  },
  {
    id: "bromine",
    un: "1744",
    cas: "7726-95-6",
    ergGuide: "154",
    labels: { fr: "Brome", ar: "البروم", en: "Bromine" },
    synonyms: ["Br2", "dibrome"],
    hazardClass: "8",
    state: "liquid",
    small: { isolationM: 60, protectDayKm: 0.4, protectNightKm: 1.2 },
    large: { isolationM: 400, protectDayKm: 2.8, protectNightKm: 6.0 },
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide rouge-brun très dense, vapeurs rousses, odeur suffocante.",
      vaporDensity: 5.5,
      boilingPointC: 59,
      behaviour: "Vapeur cinq fois plus lourde que l'air : nappe basse, persistante, nettement visible.",
      health: "Brûlures cutanées et oculaires sévères ; atteinte pulmonaire par inhalation.",
      fire: "Ininflammable mais comburant puissant : enflamme les matières organiques au contact.",
      reactivity: "Réagit violemment avec l'ammoniac, les métaux en poudre, les matières combustibles.",
      ppe: "Tenue étanche aux liquides et vapeurs, ARI. Ne pas utiliser d'eau en jet direct sur la nappe.",
    },
  },
  {
    id: "nitric-acid-fuming",
    un: "2032",
    cas: "7697-37-2",
    ergGuide: "157",
    labels: { fr: "Acide nitrique fumant rouge", ar: "حمض النيتريك المدخن", en: "Red fuming nitric acid" },
    synonyms: ["RFNA", "acide nitrique fumant"],
    hazardClass: "8",
    state: "liquid",
    small: { isolationM: 30, protectDayKm: 0.2, protectNightKm: 0.6 },
    large: { isolationM: 150, protectDayKm: 1.0, protectNightKm: 2.5 },
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide rouge-brun fumant, vapeurs rousses de dioxyde d'azote.",
      vaporDensity: 2.5,
      boilingPointC: 83,
      behaviour: "Dégage des vapeurs nitreuses plus lourdes que l'air, rousses et très visibles.",
      health: "Brûlures graves ; œdème pulmonaire RETARDÉ dû au dioxyde d'azote, jusqu'à 48 h après.",
      fire: "Comburant puissant : enflamme spontanément de nombreuses matières organiques.",
      reactivity: "Réaction violente avec les métaux, les alcools, les matières combustibles.",
      ppe: "Tenue étanche résistante aux acides oxydants, ARI.",
    },
  },

  // ==========================================================================
  // AJOUTS DU LOT N-3 — fiche renseignée, DISTANCES ERG À RELEVER
  //
  // Ces vingt substances complètent la couverture des matières toxiques par
  // inhalation présentes dans l'industrie, les ports et l'agriculture. Leur
  // fiche opérationnelle est utile dès maintenant ; leurs distances ne sont pas
  // renseignées, et le panache ERG leur est donc indisponible tant que la table
  // 1 n'a pas été relevée. C'est un manque VISIBLE plutôt qu'un chiffre faux.
  // ==========================================================================
  {
    id: "nitrogen-dioxide",
    un: "1067",
    cas: "10102-44-0",
    ergGuide: "124",
    labels: { fr: "Dioxyde d'azote", ar: "ثاني أكسيد النيتروجين", en: "Nitrogen dioxide" },
    synonyms: ["NO2", "peroxyde d'azote", "tétroxyde de diazote"],
    hazardClass: "2.3",
    state: "gas",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz roux à brun, odeur âcre.",
      vaporDensity: 1.6,
      boilingPointC: 21,
      behaviour: "Plus lourd que l'air. La couleur rousse du nuage en marque l'étendue.",
      health: "Œdème pulmonaire RETARDÉ, jusqu'à 48 h après une exposition d'apparence bénigne.",
      fire: "Ininflammable, comburant puissant.",
      reactivity: "Réagit violemment avec les matières combustibles et les hydrocarbures.",
      ppe: "ARI et tenue étanche aux gaz. Surveillance médicale de 48 h de toute personne exposée.",
    },
  },
  {
    id: "methyl-bromide",
    un: "1062",
    cas: "74-83-9",
    ergGuide: "123",
    labels: { fr: "Bromure de méthyle", ar: "بروميد الميثيل", en: "Methyl bromide" },
    synonyms: ["CH3Br", "bromométhane"],
    hazardClass: "2.3",
    state: "gas",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore, PRATIQUEMENT INODORE aux concentrations dangereuses.",
      vaporDensity: 3.3,
      boilingPointC: 4,
      behaviour:
        "Trois fois plus lourd que l'air, s'accumule dans les cales, les silos et les locaux de fumigation. " +
        "L'absence d'odeur interdit toute détection sensorielle.",
      health: "Neurotoxique ; effets retardés de plusieurs heures. Atteintes rénales et pulmonaires.",
      fire: "Difficilement inflammable.",
      reactivity: "Attaque l'aluminium et le magnésium.",
      ppe: "ARI obligatoire, détection instrumentale continue. Fumigation portuaire : vérifier le dégazage avant ouverture.",
    },
  },
  {
    id: "methyl-isocyanate",
    un: "2480",
    cas: "624-83-9",
    ergGuide: "155",
    labels: { fr: "Isocyanate de méthyle", ar: "أيزوسيانات الميثيل", en: "Methyl isocyanate" },
    synonyms: ["MIC"],
    hazardClass: "6.1",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide incolore très volatil, odeur piquante.",
      vaporDensity: 2.0,
      boilingPointC: 39,
      behaviour: "Vapeur deux fois plus lourde que l'air, se répand au sol sur de longues distances.",
      health: "Extrêmement toxique par inhalation ; lésions pulmonaires et oculaires graves et durables.",
      fire: "Très inflammable.",
      reactivity:
        "RÉAGIT VIOLEMMENT AVEC L'EAU en dégageant de la chaleur et du gaz — ne jamais noyer un épandage. " +
        "Polymérisation exothermique possible en récipient fermé.",
      ppe: "ARI et tenue étanche aux gaz. Aucun emploi d'eau sur le produit.",
    },
  },
  {
    id: "acrolein",
    un: "1092",
    cas: "107-02-8",
    ergGuide: "131P",
    labels: { fr: "Acroléine", ar: "الأكرولين", en: "Acrolein" },
    synonyms: ["prop-2-énal", "aldéhyde acrylique"],
    hazardClass: "6.1",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide incolore à jaunâtre, odeur âcre de graisse brûlée, très irritante.",
      vaporDensity: 1.9,
      boilingPointC: 53,
      behaviour: "Vapeur plus lourde que l'air. Fort pouvoir lacrymogène, qui donne l'alerte avant le danger létal.",
      health: "Lésions pulmonaires graves ; œdème possiblement retardé.",
      fire: "Très inflammable.",
      reactivity: "POLYMÉRISE violemment sous l'effet de la chaleur, de la lumière ou en présence de bases.",
      ppe: "ARI et tenue étanche. Surveiller l'échauffement des capacités — signe de polymérisation en cours.",
    },
  },
  {
    id: "carbon-monoxide",
    un: "1016",
    cas: "630-08-0",
    ergGuide: "119",
    labels: { fr: "Monoxyde de carbone", ar: "أول أكسيد الكربون", en: "Carbon monoxide" },
    synonyms: ["CO"],
    hazardClass: "2.3",
    state: "gas",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore, INODORE et sans saveur — indétectable sans instrument.",
      vaporDensity: 0.97,
      boilingPointC: -191,
      behaviour: "Densité proche de l'air : se mélange uniformément, sans couche haute ni basse.",
      health: "Asphyxiant : se fixe sur l'hémoglobine. Céphalées, confusion, puis perte de connaissance.",
      fire: "Inflammable.",
      reactivity: "Réagit avec les oxydants forts.",
      ppe: "ARI, détection instrumentale. Oxygénothérapie normobare, voire hyperbare, pour les intoxiqués.",
    },
  },
  {
    id: "phosphine",
    un: "2199",
    cas: "7803-51-2",
    ergGuide: "119",
    labels: { fr: "Phosphine", ar: "الفوسفين", en: "Phosphine" },
    synonyms: ["PH3", "hydrogène phosphoré"],
    hazardClass: "2.3",
    state: "gas",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore, odeur d'ail ou de poisson pourri.",
      vaporDensity: 1.2,
      boilingPointC: -88,
      behaviour: "Plus lourd que l'air. Dégagé par les pastilles de phosphure d'aluminium au contact de l'humidité.",
      health: "Très toxique ; atteinte pulmonaire, hépatique et cardiaque. Effets pouvant être retardés.",
      fire: "Peut s'enflammer SPONTANÉMENT à l'air.",
      reactivity: "Réagit violemment avec les oxydants et les halogènes.",
      ppe: "ARI et tenue étanche. Fumigation de céréales : ventiler et mesurer avant toute pénétration.",
    },
  },
  {
    id: "arsine",
    un: "2188",
    cas: "7784-42-1",
    ergGuide: "119",
    labels: { fr: "Arsine", ar: "الأرسين", en: "Arsine" },
    synonyms: ["AsH3", "hydrogène arsénié"],
    hazardClass: "2.3",
    state: "gas",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore, faible odeur d'ail — non fiable comme alerte.",
      vaporDensity: 2.7,
      boilingPointC: -62,
      behaviour: "Nettement plus lourd que l'air.",
      health:
        "Détruit les globules rouges. Signes RETARDÉS de 2 à 24 h : urines foncées, ictère, insuffisance rénale. " +
        "Toute personne exposée est adressée à l'hôpital, même asymptomatique.",
      fire: "Inflammable.",
      reactivity: "Se forme lorsqu'un acide attaque un métal contenant de l'arsenic.",
      ppe: "ARI et tenue étanche. Surveillance biologique des exposés.",
    },
  },
  {
    id: "boron-trifluoride",
    un: "1008",
    cas: "7637-07-2",
    ergGuide: "125",
    labels: { fr: "Trifluorure de bore", ar: "ثلاثي فلوريد البورون", en: "Boron trifluoride" },
    synonyms: ["BF3"],
    hazardClass: "2.3",
    state: "gas",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore fumant abondamment à l'air humide, odeur suffocante.",
      vaporDensity: 2.4,
      boilingPointC: -100,
      behaviour: "Plus lourd que l'air ; le brouillard blanc dense marque l'étendue du rejet.",
      health: "Brûlures des voies respiratoires ; atteinte rénale possible.",
      fire: "Ininflammable.",
      reactivity: "Réaction violente avec l'eau, produisant des acides corrosifs. Attaque le verre.",
      ppe: "ARI et tenue étanche aux vapeurs acides.",
    },
  },
  {
    id: "sulfur-trioxide",
    un: "1829",
    cas: "7446-11-9",
    ergGuide: "137",
    labels: { fr: "Trioxyde de soufre", ar: "ثالث أكسيد الكبريت", en: "Sulfur trioxide" },
    synonyms: ["SO3", "anhydride sulfurique"],
    hazardClass: "8",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide ou solide fumant, brouillard blanc dense à l'air.",
      vaporDensity: 2.8,
      boilingPointC: 45,
      behaviour: "Fume violemment à l'air humide, formant un aérosol d'acide sulfurique persistant.",
      health: "Brûlures profondes de la peau, des yeux et des voies respiratoires.",
      fire: "Ininflammable ; enflamme les matières organiques au contact.",
      reactivity: "RÉACTION VIOLENTE ET EXOTHERMIQUE AVEC L'EAU — projections d'acide. Ne jamais noyer.",
      ppe: "Tenue étanche résistante aux acides, ARI. Endiguer et absorber à sec.",
    },
  },
  {
    id: "chloropicrin",
    un: "1580",
    cas: "76-06-2",
    ergGuide: "154",
    labels: { fr: "Chloropicrine", ar: "الكلوروبكرين", en: "Chloropicrin" },
    synonyms: ["trichloronitrométhane", "PS"],
    hazardClass: "6.1",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide huileux incolore à jaunâtre, odeur intense très lacrymogène.",
      vaporDensity: 5.7,
      boilingPointC: 112,
      behaviour: "Vapeur près de six fois plus lourde que l'air : nappe très basse et persistante.",
      health: "Puissant lacrymogène et suffocant ; œdème pulmonaire aux fortes expositions.",
      fire: "Ininflammable, mais peut détoner sous choc violent ou échauffement.",
      reactivity: "Se décompose à la chaleur en phosgène et en oxydes d'azote.",
      ppe: "ARI et tenue étanche. Le pouvoir lacrymogène gêne l'intervention avant même le seuil toxique.",
    },
  },
  {
    id: "dimethyl-sulfate",
    un: "1595",
    cas: "77-78-1",
    ergGuide: "156",
    labels: { fr: "Sulfate de diméthyle", ar: "كبريتات ثنائي الميثيل", en: "Dimethyl sulfate" },
    synonyms: ["DMS"],
    hazardClass: "6.1",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide huileux incolore, odeur FAIBLE d'oignon — pas d'alerte olfactive utile.",
      vaporDensity: 4.4,
      boilingPointC: 188,
      behaviour: "Vapeur très lourde. Peu volatil à froid, dangereux dès qu'il est chauffé.",
      health:
        "Effets RETARDÉS de plusieurs heures : brûlures cutanées et oculaires, œdème pulmonaire. " +
        "Cancérogène. L'absence de douleur immédiate a coûté des vies.",
      fire: "Combustible.",
      reactivity: "S'hydrolyse lentement dans l'eau en acide sulfurique et méthanol.",
      ppe: "Tenue étanche et ARI. Décontamination immédiate même sans symptôme.",
    },
  },
  {
    id: "titanium-tetrachloride",
    un: "1838",
    cas: "7550-45-0",
    ergGuide: "137",
    labels: { fr: "Tétrachlorure de titane", ar: "رابع كلوريد التيتانيوم", en: "Titanium tetrachloride" },
    synonyms: ["TiCl4"],
    hazardClass: "8",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide incolore à jaune, fume abondamment à l'air.",
      vaporDensity: 6.5,
      boilingPointC: 136,
      behaviour: "Épais brouillard blanc d'acide chlorhydrique à l'air humide, très visible et très lourd.",
      health: "Brûlures des voies respiratoires, des yeux et de la peau par l'acide formé.",
      fire: "Ininflammable.",
      reactivity: "RÉAGIT VIOLEMMENT AVEC L'EAU. Endiguer à sec, ne pas noyer.",
      ppe: "Tenue étanche aux acides, ARI.",
    },
  },
  {
    id: "oleum",
    un: "1831",
    cas: "8014-95-7",
    ergGuide: "137",
    labels: { fr: "Oléum (acide sulfurique fumant)", ar: "الأوليوم", en: "Oleum" },
    synonyms: ["acide sulfurique fumant", "acide disulfurique"],
    hazardClass: "8",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide huileux fumant, brouillard blanc dense.",
      vaporDensity: 2.8,
      behaviour: "Dégage du trioxyde de soufre qui forme un aérosol acide persistant et rampant.",
      health: "Brûlures profondes ; atteinte pulmonaire sévère par l'aérosol.",
      fire: "Ininflammable ; carbonise les matières organiques.",
      reactivity: "RÉACTION TRÈS EXOTHERMIQUE AVEC L'EAU, avec projections. Endiguer, absorber à sec.",
      ppe: "Tenue étanche résistante aux acides, ARI.",
    },
  },
  {
    id: "phosphorus-oxychloride",
    un: "1810",
    cas: "10025-87-3",
    ergGuide: "137",
    labels: { fr: "Oxychlorure de phosphore", ar: "أوكسي كلوريد الفوسفور", en: "Phosphorus oxychloride" },
    synonyms: ["POCl3"],
    hazardClass: "6.1",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide incolore fumant, odeur âcre et piquante.",
      vaporDensity: 5.3,
      boilingPointC: 106,
      behaviour: "Vapeur très lourde ; fume à l'air humide en dégageant de l'acide chlorhydrique.",
      health: "Brûlures graves ; œdème pulmonaire retardé.",
      fire: "Ininflammable.",
      reactivity: "RÉACTION VIOLENTE AVEC L'EAU. Attaque de nombreux métaux.",
      ppe: "Tenue étanche, ARI. Endiguement à sec.",
    },
  },
  {
    id: "phosphorus-trichloride",
    un: "1809",
    cas: "7719-12-2",
    ergGuide: "137",
    labels: { fr: "Trichlorure de phosphore", ar: "ثلاثي كلوريد الفوسفور", en: "Phosphorus trichloride" },
    synonyms: ["PCl3"],
    hazardClass: "6.1",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide incolore fumant, odeur piquante.",
      vaporDensity: 4.8,
      boilingPointC: 76,
      behaviour: "Fume à l'air humide. Vapeur nettement plus lourde que l'air.",
      health: "Brûlures graves des voies respiratoires et de la peau ; œdème pulmonaire retardé.",
      fire: "Ininflammable, mais enflamme certaines matières organiques.",
      reactivity: "RÉACTION VIOLENTE AVEC L'EAU, dégageant HCl et acide phosphoreux.",
      ppe: "Tenue étanche aux acides, ARI.",
    },
  },
  {
    id: "thionyl-chloride",
    un: "1836",
    cas: "7719-09-7",
    ergGuide: "137",
    labels: { fr: "Chlorure de thionyle", ar: "كلوريد الثيونيل", en: "Thionyl chloride" },
    synonyms: ["SOCl2"],
    hazardClass: "8",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide incolore à jaune, fumant, odeur suffocante.",
      vaporDensity: 4.1,
      boilingPointC: 76,
      behaviour: "Fume à l'air. Se décompose en HCl et SO2, deux gaz plus lourds que l'air.",
      health: "Brûlures graves ; atteinte pulmonaire par les gaz de décomposition.",
      fire: "Ininflammable.",
      reactivity: "RÉACTION VIOLENTE AVEC L'EAU. Présent dans certaines batteries au lithium.",
      ppe: "Tenue étanche, ARI. Absorption à sec.",
    },
  },
  {
    id: "chlorosulfonic-acid",
    un: "1754",
    cas: "7790-94-5",
    ergGuide: "137",
    labels: { fr: "Acide chlorosulfonique", ar: "حمض الكلوروسلفونيك", en: "Chlorosulfonic acid" },
    synonyms: ["HSO3Cl"],
    hazardClass: "8",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide incolore à brun, fumant violemment à l'air.",
      vaporDensity: 4.0,
      boilingPointC: 152,
      behaviour: "Brouillard blanc très dense d'acides sulfurique et chlorhydrique.",
      health: "Brûlures profondes ; atteinte pulmonaire sévère.",
      fire: "Ininflammable ; carbonise les matières organiques.",
      reactivity: "RÉACTION EXPLOSIVE AVEC L'EAU. Ne jamais approcher d'eau du produit pur.",
      ppe: "Tenue étanche aux acides, ARI. Endiguer à sec, absorber sur matériau inerte.",
    },
  },
  {
    id: "acrylonitrile",
    un: "1093",
    cas: "107-13-1",
    ergGuide: "131P",
    labels: { fr: "Acrylonitrile", ar: "الأكريلونتريل", en: "Acrylonitrile" },
    synonyms: ["cyanure de vinyle", "prop-2-énenitrile"],
    hazardClass: "3",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide incolore, odeur faiblement piquante d'oignon ou d'ail.",
      vaporDensity: 1.8,
      boilingPointC: 77,
      behaviour: "Vapeur plus lourde que l'air, inflammable, pouvant refluer vers une source d'allumage.",
      health: "Toxicité de type cyanhydrique ; cancérogène. Antidote du cyanure applicable.",
      fire: "Très inflammable. La combustion dégage du cyanure d'hydrogène.",
      reactivity: "POLYMÉRISE violemment en présence de bases fortes ou sous l'effet de la chaleur.",
      ppe: "ARI et tenue étanche. Prévoir l'antidote du cyanure.",
    },
  },
  {
    id: "carbon-disulfide",
    un: "1131",
    cas: "75-15-0",
    ergGuide: "131",
    labels: { fr: "Disulfure de carbone", ar: "ثنائي كبريتيد الكربون", en: "Carbon disulfide" },
    synonyms: ["CS2", "sulfure de carbone"],
    hazardClass: "3",
    state: "liquid",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Liquide incolore à jaunâtre, odeur de chou pourri (le produit pur sent l'éther).",
      vaporDensity: 2.6,
      boilingPointC: 46,
      behaviour: "Vapeur lourde qui reflue au sol vers les sources d'allumage.",
      health: "Neurotoxique ; atteinte du système nerveux central et périphérique.",
      fire:
        "EXTRÊMEMENT INFLAMMABLE. Température d'auto-inflammation d'environ 90 °C : une simple " +
        "canalisation de vapeur, une ampoule, suffisent à l'enflammer.",
      reactivity: "Réagit avec les oxydants. Se conserve sous eau.",
      ppe: "ARI, tenue étanche, matériel antidéflagrant. Supprimer toute source d'ignition sur un large périmètre.",
    },
  },
  {
    id: "chlorine-trifluoride",
    un: "1749",
    cas: "7790-91-2",
    ergGuide: "124",
    labels: { fr: "Trifluorure de chlore", ar: "ثلاثي فلوريد الكلور", en: "Chlorine trifluoride" },
    synonyms: ["ClF3"],
    hazardClass: "2.3",
    state: "gas",
    ergVerified: false,
    sheetVerified: false,
    sheet: {
      appearance: "Gaz incolore à jaune verdâtre, odeur douceâtre et suffocante.",
      vaporDensity: 3.2,
      boilingPointC: 12,
      behaviour: "Plus lourd que l'air.",
      health: "Brûlures chimiques et thermiques graves ; atteinte pulmonaire majeure.",
      fire:
        "Comburant parmi les plus violents connus : enflamme le verre, le sable, le béton, les tissus, " +
        "et brûle des matériaux réputés incombustibles.",
      reactivity:
        "RÉAGIT EXPLOSIVEMENT AVEC L'EAU et avec presque toute matière organique. Aucun agent d'extinction " +
        "classique n'est applicable : isoler, laisser consumer, protéger les abords.",
      ppe: "Tenue étanche, ARI. Ne pas tenter d'éteindre — refroidir les capacités voisines à distance.",
    },
  },
];
